### ISSUE TITLE
Re-enable Travis CI

### ISSUE THREAD

**Issue by daniel-rikowski** [piwik/piwik-ruby-api#17]
It looks like changes to this repository no longer trigger a Travis CI run. This seems to be the same problem as https://github.com/travis-ci/travis-ci/issues/5629 
Perhaps someone with access to the Travis CI account can try the proposed fix of enabling this repo directly from the Travis CI account instead from Github.

**Comment by Achillefs** [comment]
Hi, I've re-enabled travis, CI should work now.

**Comment by daniel-rikowski** [comment]
Thank you! 
I wanted to sort this out before I'll setup Travis to use different Gemfiles. (Because of the wide range of supported Ruby and Rails/ActiveSupport versions and their individual dependencies a single Gemfile doesn't work anymore)

**Comment by Achillefs** [comment]
Makes sense!
